FROM alpine:3.7

MAINTAINER Julien Neuhart <j.neuhart@thecodingmachine.com>

# |--------------------------------------------------------------------------
# | OpenSSL
# |--------------------------------------------------------------------------
# |
# | Installs openssl command, which is required for generating the self-signed
# | certificate, the .htdigest file and the Graylog passwords.
# |

ENV OPENSSL_VERSION 1.0.2n-r0

RUN apk --no-cache add openssl=$OPENSSL_VERSION